"""
MetaPilot AI - HTML Exporter

Exports data to HTML format.
"""

import logging
import json
from typing import Any, Dict, List, Optional, Union
from datetime import datetime
from pathlib import Path

from .export_manager import Exporter, ExportConfig, ExportResult, ExportFormat

logger = logging.getLogger(__name__)


class HTMLExporter(Exporter):
    """
    Exports data to HTML format.
    
    Creates standalone HTML documents with styling.
    """
    
    def __init__(self, config: Optional[ExportConfig] = None):
        """
        Initialize the HTML exporter.
        
        Args:
            config: Export configuration
        """
        super().__init__(config)
    
    async def export(self, data: Any, output_path: Optional[str] = None) -> ExportResult:
        """
        Export data to an HTML file.
        
        Args:
            data: Data to export
            output_path: Optional output file path
        
        Returns:
            ExportResult
        """
        import time
        start_time = time.time()
        
        try:
            # Convert data to HTML
            html_content = await self.export_to_string(data)
            
            # Determine output path
            if output_path is None:
                output_dir = self._ensure_output_dir()
                filename = self._generate_filename("html")
                output_path = str(output_dir / filename)
            
            # Write to file
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w', encoding=self.config.encoding) as f:
                f.write(html_content)
            
            # Get file size
            file_size = Path(output_path).stat().st_size
            
            return ExportResult(
                success=True,
                file_path=output_path,
                content=html_content,
                format=ExportFormat.HTML,
                size=file_size,
                export_time=time.time() - start_time,
                metadata={
                    "type": "html",
                    "encoding": self.config.encoding
                }
            )
            
        except Exception as e:
            logger.error(f"Error exporting to HTML: {e}")
            return ExportResult(
                success=False,
                error=str(e),
                export_time=time.time() - start_time
            )
    
    async def export_to_string(self, data: Any) -> str:
        """
        Convert data to HTML string.
        
        Args:
            data: Data to convert
        
        Returns:
            HTML content
        """
        # Generate HTML document
        title = self.config.filename_prefix or "Export"
        
        body_content = self._format_body(data)
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="{self.config.encoding}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        {self._get_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{title}</h1>
            <p class="timestamp">Exported on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </header>
        
        <main>
            {body_content}
        </main>
        
        <footer>
            <p>Generated by MetaPilot AI</p>
        </footer>
    </div>
</body>
</html>"""
        
        return html
    
    def _get_styles(self) -> str:
        """Get CSS styles for the HTML document."""
        return """
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
            padding: 20px;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        
        header {
            margin-bottom: 40px;
            border-bottom: 1px solid #eee;
            padding-bottom: 20px;
        }
        
        header h1 {
            color: #2c3e50;
            margin-bottom: 10px;
        }
        
        .timestamp {
            color: #7f8c8d;
            font-size: 0.9em;
        }
        
        main {
            margin-bottom: 40px;
        }
        
        footer {
            text-align: center;
            color: #7f8c8d;
            font-size: 0.8em;
            border-top: 1px solid #eee;
            padding-top: 20px;
        }
        
        h1, h2, h3, h4, h5, h6 {
            margin-top: 1.5em;
            margin-bottom: 0.5em;
            color: #2c3e50;
        }
        
        p {
            margin-bottom: 1em;
        }
        
        ul, ol {
            margin-bottom: 1em;
            padding-left: 2em;
        }
        
        li {
            margin-bottom: 0.5em;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 1.5em;
        }
        
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }
        
        th {
            background-color: #f8f9fa;
            font-weight: 600;
        }
        
        tr:hover {
            background-color: #f5f5f5;
        }
        
        pre {
            background-color: #2d3436;
            color: #f8f9fa;
            padding: 16px;
            border-radius: 4px;
            overflow-x: auto;
            margin-bottom: 1em;
        }
        
        code {
            background-color: #f0f0f0;
            padding: 2px 4px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }
        
        pre code {
            background-color: transparent;
            padding: 0;
        }
        
        blockquote {
            border-left: 4px solid #3498db;
            padding-left: 16px;
            margin-left: 0;
            color: #555;
            font-style: italic;
        }
        
        .section {
            margin-bottom: 2em;
            padding: 16px;
            background-color: #f9f9f9;
            border-radius: 4px;
        }
        
        .section h2 {
            margin-top: 0;
        }
        
        .key-value {
            margin-bottom: 0.5em;
            padding: 8px;
            background-color: #f5f5f5;
            border-radius: 4px;
        }
        
        .key-value .key {
            font-weight: 600;
            color: #2c3e50;
        }
        """
    
    def _format_body(self, data: Any) -> str:
        """Format the body content based on data type."""
        if isinstance(data, str):
            return self._format_text(data)
        elif isinstance(data, dict):
            return self._format_dict(data)
        elif isinstance(data, list):
            return self._format_list(data)
        else:
            return self._format_primitive(data)
    
    def _format_text(self, text: str) -> str:
        """Format plain text for HTML."""
        # Escape HTML special characters
        import html
        return html.escape(text).replace('\n', '<br>')
    
    def _format_dict(self, data: Dict[str, Any], level: int = 0) -> str:
        """Format dictionary as HTML."""
        if level == 0:
            # Top level - use sections
            parts = []
            for key, value in data.items():
                header = f"<h2>{self._escape_html(key)}</h2>"
                if isinstance(value, dict):
                    content = f"<div class=\"section\">\n{header}\n{self._format_dict(value, level + 1)}\n</div>"
                elif isinstance(value, list):
                    content = f"<div class=\"section\">\n{header}\n{self._format_list(value, level + 1)}\n</div>"
                else:
                    content = f"<div class=\"key-value\">\n<span class=\"key\">{self._escape_html(key)}:</span>\n{self._format_primitive(value)}\n</div>"
                parts.append(content)
            return "\n".join(parts)
        else:
            # Nested - use table
            rows = []
            for key, value in data.items():
                if isinstance(value, dict):
                    value_html = self._format_dict(value, level + 1)
                elif isinstance(value, list):
                    value_html = self._format_list(value, level + 1)
                else:
                    value_html = self._format_primitive(value)
                
                rows.append(f"<tr><td><strong>{self._escape_html(key)}</strong></td><td>{value_html}</td></tr>")
            
            return f"<table>\n{''.join(rows)}\n</table>"
    
    def _format_list(self, data: List[Any], level: int = 0) -> str:
        """Format list as HTML."""
        if not data:
            return "<p><em>(empty)</em></p>"
        
        # Check if all items are dicts (table format)
        if all(isinstance(item, dict) for item in data):
            return self._format_table(data)
        
        # Otherwise, use list format
        items = []
        for item in data:
            if isinstance(item, dict):
                item_html = self._format_dict(item, level + 1)
            elif isinstance(item, list):
                item_html = self._format_list(item, level + 1)
            else:
                item_html = self._format_primitive(item)
            items.append(f"<li>{item_html}</li>")
        
        return f"<ul>\n{''.join(items)}\n</ul>"
    
    def _format_table(self, data: List[Dict[str, Any]]) -> str:
        """Format data as an HTML table."""
        if not data:
            return ""
        
        # Get all keys
        keys = set()
        for row in data:
            keys.update(row.keys())
        
        sorted_keys = sorted(keys)
        
        # Create header
        header = "<tr>" + "".join(f"<th>{self._escape_html(k)}</th>" for k in sorted_keys) + "</tr>"
        
        # Create rows
        rows = []
        for row in data:
            cells = []
            for key in sorted_keys:
                value = row.get(key, "")
                if value is None:
                    value = ""
                elif isinstance(value, (dict, list)):
                    value = json.dumps(value)
                cells.append(f"<td>{self._escape_html(str(value))}</td>")
            rows.append(f"<tr>{"".join(cells)}</tr>")
        
        return f"<table>\n{header}\n{''.join(rows)}\n</table>"
    
    def _format_primitive(self, value: Any) -> str:
        """Format primitive values for HTML."""
        if value is None:
            return "<em>null</em>"
        elif isinstance(value, bool):
            return '<span style="color: green;">✓</span>' if value else '<span style="color: red;">✗</span>'
        elif isinstance(value, datetime):
            return f"<time>{value.isoformat()}</time>"
        elif isinstance(value, str):
            # Check if it's a long string (code block)
            if len(value) > 100 or '\n' in value:
                return f"<pre><code>{self._escape_html(value)}</code></pre>"
            return self._escape_html(value)
        else:
            return self._escape_html(str(value))
    
    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters."""
        import html
        return html.escape(str(text))


# Register with export manager
def register_html_exporter(export_manager: Any, config: Optional[ExportConfig] = None) -> None:
    """Register the HTML exporter with an export manager."""
    exporter = HTMLExporter(config)
    export_manager.register_exporter(ExportFormat.HTML, exporter)
