"""# This is the alembic script template for generating migrations.
# It is used by Alembic to generate new migration files.
# Do not modify this file directly.
"""
from alembic import op
import sqlalchemy as sa


# ### commands auto generated by Alembic - please adjust! ###

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass